# Generated by Django 3.1.7 on 2021-03-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_link',
            field=models.URLField(max_length=50),
        ),
    ]
